services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug


  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

